# Generated by Django 5.1.5 on 2025-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(unique=True, verbose_name='Идентификатор сервера')),
                ('cpu', models.SmallIntegerField(default=0, verbose_name='Количество процессорных ядер')),
                ('ram', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Объем оперативной памяти (Мб)')),
                ('hdd', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Объем дискового пространства (Гб)')),
                ('status', models.CharField(choices=[('started', 'Запущен'), ('blocked', 'Заблокирован'), ('stopped', 'Остановлен')], verbose_name='Статус сервера')),
            ],
        ),
    ]
